language: generic 

sudo: required 
services:
  -docker 

before_install:
  - docker build -t WendyHarris/docker-react -f Dockerfile.dev . 

script:
  -docker run -e CI=true WendyHarris/docker-react npm run test
